### ISSUE TITLE
Parsing problem with latest version

### ISSUE THREAD

**Issue by beeb** [dtolnay/rust-toolchain#64]
Today I'm getting this error in CI:

`dtolnay/rust-toolchain/stable/action.yml (Line: 69, Col: 7): Unexpected value 'if'`

And indeed somehow even the syntax highlighting shows something weird:

https://github.com/dtolnay/rust-toolchain/blob/stable/action.yml#L69-L70

Extended error:

```
GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. dtolnay/rust-toolchain/stable/action.yml (Line: 69, Col: 7): Unexpected value 'if'
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManif[...]
```

**Comment by beeb** [comment]
The problem fixed itself, maybe a github issue
